{
    'name': 'Employee Item Request',
    'version': '2.3.0',
    'summary': 'Department-based item request and issuance workflow',
    'description': 'Employees request items through their department heads. Inventory approves and issues stock.',
    'author': 'Lilo',
    'category': 'Inventory',
    'depends': ['stock', 'hr'],
    'data': [
        'data/sequence.xml',
        'data/stock_location_data.xml',
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/employee_request_views.xml',
        'views/stock_picking_inherit_views.xml',
    ],
    'license': 'LGPL-3',
    'installable': True,
    'application': False,
}
